### ISSUE TITLE
`Yield` effect unused in `aio`

### ISSUE THREAD

**Issue by Sudha247** [ocaml-multicore/effects-examples#33]
https://github.com/ocaml-multicore/effects-examples/blob/master/aio/aio.ml#L16 defines `Yield` here, but it's not used anywhere in the rest of the scheduler. Was it supposed to be used somewhere or could we remove it?

(pointed out by @Leonidas-from-XIV)

**Comment by dhil** [comment]
I suppose it is unused in this example (the `echo` server), and as such it could probably go. In general it can be quite useful as a primitive to force preemption rather than having to perform an IO operation.

**Comment by Sudha247** [comment]
Fixed by #38.
